version: "3.8"

services:
  palworld:
    image: jtmckay/palworld:latest
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - COMMUNITY_SERVER=${COMMUNITY_SERVER}
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_DESCRIPTION=${SERVER_DESCRIPTION}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - WORLD_OPTION_SETTINGS=${WORLD_OPTION_SETTINGS}
    volumes:
      - ./game:/palworld
    restart: always
    network_mode: bridge
    # command: ["sleep", "infinity"]
    ports:
      - target: 8211 # gamerserver port inside of the container
        published: 8211 # gamerserver port on your host
        protocol: udp
        mode: host
      - target: 27015 # gamerserver port inside of the container
        published: 27015 # gamerserver port on your host
        mode: host
      - target: 25575 # rcon port inside of the container
        published: 25575 # rcon port on your host
        protocol: tcp
        mode: host
