FROM cm2network/steamcmd:ubuntu-22

# Incoming arguments as environment variables
ARG GAME_PATH
ENV GAME_PATH=${GAME_PATH}

ARG PUBLIC_IP
ENV PUBLIC_IP=${PUBLIC_IP}

ARG PUBLIC_PORT
ENV PUBLIC_PORT=${PUBLIC_PORT}

ARG MAX_PLAYERS
ENV MAX_PLAYERS=${MAX_PLAYERS}

ARG COMMUNITY_SERVER
ENV COMMUNITY_SERVER=${COMMUNITY_SERVER}

ARG SERVER_NAME
ENV SERVER_NAME=${SERVER_NAME}

ARG SERVER_DESCRIPTION
ENV SERVER_DESCRIPTION=${SERVER_DESCRIPTION}

ARG SERVER_PASSWORD
ENV SERVER_PASSWORD=${SERVER_PASSWORD}

ARG ADMIN_PASSWORD
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Set environment variables
ENV TIMEZONE=Europe/Berlin \
    DEBIAN_FRONTEND=noninteractive \
    PUID=0 \
    PGID=0 \
    ALWAYS_UPDATE_ON_START=true \
    MULTITHREAD_ENABLED=true

# Palworld

WORKDIR $GAME_PATH

VOLUME [ "/palworld" ]

EXPOSE $PUBLIC_PORT/udp

ADD servermanager.sh /servermanager.sh

CMD ["/servermanager.sh"]
